# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Anaxago\CoreBundle\Entity\User:
            algorithm: bcrypt

    providers:
        anaxago_provider:
            entity:
                class: AnaxagoCoreBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
        api_provider:
            id: anaxago_core_security_api_user_provider

    firewalls:

        #api publique
        api_public:
            stateless: true
            pattern: ^/api/[A-Za-z0-9]+/project
            anonymous: ~

        #api en mode connecté
        api:
            stateless: true
            pattern: ^/api
            simple_preauth:
                provider: api_provider
                authenticator: anaxago_core_security_api_authenticator
            #context: apicontext

        main:
            provider: anaxago_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
