<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * nb total de projets
     *
     * @return int
     */
    public function count() : int
    {
        return $this->createQueryBuilder('p')
        ->select('count(p.id)')
        ->getQuery()
        ->getSingleScalarResult();
    }

    /**
     * retrouver la liste des projets appartenant à une pagination
     *
     * @param int $page
     * @param int $max
     * @return array
     */
    public function findAll($page=1, $max=10)
    {
        $firstResult = ($page - 1) * $max;

        return $this->createQueryBuilder('b')
            ->select()
            ->setFirstResult($firstResult)
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();
    }
}
