
projects_list:
  path: /project
  methods: [GET]
  defaults: { _controller: AnaxagoCoreBundle:Api\Project:list}

projects_read:
  path: /project/{id}
  methods: [GET]
  defaults: { _controller: AnaxagoCoreBundle:Api\Project:read}

proposal_list:
  path: /proposal
  methods: [GET]
  defaults: { _controller: AnaxagoCoreBundle:Api\Proposal:list}

proposal_create:
  path: /proposal/project/{projectId}
  methods: [POST]
  defaults: { _controller: AnaxagoCoreBundle:Api\Proposal:create}


proposal_read:
  path: /proposal/{id}
  methods: [GET]
  defaults: { _controller: AnaxagoCoreBundle:Api\Proposal:read}

proposal_update:
  path: /proposal/{id}
  methods: [PUT]
  defaults: { _controller: AnaxagoCoreBundle:Api\Proposal:update}

proposal_delete:
  path: /proposal/{id}
  methods: [DELETE]
  defaults: { _controller: AnaxagoCoreBundle:Api\Proposal:delete}