services:

  anaxago_core_repository_project:
    class: Anaxago\CoreBundle\Repository\ProjectRepository
    factory : ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - Anaxago\CoreBundle\Entity\Project

  anaxago_core_repository_proposal:
    class: Anaxago\CoreBundle\Repository\ProposalRepository
    factory: ['@doctrine.orm.entity_manager', 'getRepository']
    arguments:
      - Anaxago\CoreBundle\Entity\Proposal


  anaxago_core_service_api_project:
    class: Anaxago\CoreBundle\Service\Api\ProjectService
    arguments: ['@anaxago_core_repository_project']

  anaxago_core_service_api_proposal:
    class: Anaxago\CoreBundle\Service\Api\ProposalService
    arguments: ['@anaxago_core_repository_proposal']
