services:

  anaxago_core_service_api_project:
    class: Anaxago\CoreBundle\Service\Api\ProjectService
    arguments: []

  anaxago_core_service_api_proposal:
    class: Anaxago\CoreBundle\Service\Api\ProposalService
    arguments: []
